# Generated by Django 5.2.5 on 2025-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
