# Generated by Django 4.2.24 on 2025-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterprofile',
            name='cert_image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
