# Generated by Django 4.2.24 on 2025-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsitting', '0002_alter_sitterprofile_cert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
